### ISSUE TITLE
Update PDF.js to newer/latest

### ISSUE THREAD

**Issue by asmecher** [pkp/pdfJsViewer#13]
See http://forum.pkp.sfu.ca/t/problems-with-pdfjsviewer-plugin-in-omp-1-2/27006/4

**Comment by asmecher** [comment]
To update this yourself, download the latest stable PDF.js from https://mozilla.github.io/pdf.js/getting_started/#download (currently v1.5.188). Save the .zip to your server and:

    cd plugins/generic/pdfJsViewer
    mv pdf.js pdf.js-old
    mkdir pdf.js
    cd pdf.js
    unzip /path/to/pdfjs-distribution.zip

(...replacing /path/to/pdfjs-distribution.zip with the path and name of the .zip file you downloaded.)

When you've verified that this is working, you can get rid of the `pdf.js-old` backup.

**Comment by amatsumiro** [comment]
Hi @asmecher 

First line:
>cd plugins/**viewableFiles**/pdfJsViewer

I updated but the problem continues.
I cleaned the data cache and template.
I'll talk again to the plugin folks and let you know.
Thank you a lot.

**Comment by asmecher** [comment]
@amatsumiro -- ah, it sounds like you're using OMP, not OJS. In that case, it's a different plugin from the one used in this repository, though the upgrade process will be pretty much identical.
