### ISSUE TITLE
Plugin cancels hook processing early

### ISSUE THREAD

**Issue by ctgraham** [pkp/pdfJsViewer#32]
@ajnyga notes that the hook callbacks return `true` when active, cancelling further hook processing:
https://github.com/pkp/pdfJsViewer/blob/dcf7dccf0ca36c04876ae0a5439d173ec4a228dd/PdfJsViewerPlugin.inc.php#L81
https://github.com/pkp/pdfJsViewer/blob/dcf7dccf0ca36c04876ae0a5439d173ec4a228dd/PdfJsViewerPlugin.inc.php#L111

The plugin also performs the default registration against the `HOOK_SEQUENCE_NORMAL` scheduling.
https://github.com/pkp/pdfJsViewer/blob/dcf7dccf0ca36c04876ae0a5439d173ec4a228dd/PdfJsViewerPlugin.inc.php#L24-L25

If we need to terminate additional hook processing, we should register against `HOOK_SEQUENCE_LAST` instead.  Alternately, we might evaluate whether the choice to terminate hook processing is really merited.

**Comment by asmecher** [comment]
The logic behind terminating hook processing here is to indicate that the PDF viewer really was able to accomplish the task, in case e.g. another plugin was waiting in the wings to try. I'd suggest moving the hook registration to `HOOK_SEQUENCE_LAST` (that's a good use for this feature).

**Comment by asmecher** [comment]
Merged and cherry-picked to `ojs-stable-3_1_1` -- thanks, @ctgraham and @ajnyga!
