### ISSUE TITLE
Let iframe use relative URL instead of absolute

### ISSUE THREAD

**Issue by sean-xiao-zhao7** [pkp/pdfJsViewer#34]
See https://forum.pkp.sfu.ca/t/pdf-js-viewer-fails-when-proxied-fix-and-solution/18257
The current iframe URL does not work with EZProxy setups.
EZProxy is unable to correctly calculate the base URL - it always seems to use the non-ezproxyed base URL.

After discussion with Clinton Graham, we've came up with a solution. 
I'd like to submit a PR on this repo for this fix.

**Comment by asmecher** [comment]
@sean-xiao-zhao7, please do!
