### ISSUE TITLE
fullscreen

### ISSUE THREAD

**Issue by nerijus** [pkp/pdfJsViewer#4]
Is it possible to have fullscreen button or link, like the old version has?

**Comment by asmecher** [comment]
@nerijus, there should be one in the PDF.js reader interface itself. Check the toolbar.

**Comment by nerijus** [comment]
I cannot find it. For example here - http://lmaleidykla.lt/ojs/index.php/actamedicalituanica/article/view/3045/1872

**Comment by asmecher** [comment]
For me, there's a button called "Switch to Presentation Mode" on the toolbar.

**Comment by nerijus** [comment]
Oops, found it too. Didn't think that Presentation mode means Fullscreen.

**Comment by asmecher** [comment]
Agreed, it could be more clearly named -- but that's a PDF.js issue, outside the scope of this plugin.
