### ISSUE TITLE
Browser download a viewer.html instead of showing my PDFs

### ISSUE THREAD

**Issue by jimnault** [pkp/pdfJsViewer#43]
Hi there,

I'm running the latest version of OJS with pdfJsViewer installed and enabled. When I click on any PDF links, my browser download a file named viewer.html instead of showing the PDF file as supposed... When I disable the pdfJsViewer plugin, the browser now download the PDF file as supposed to be.

Any help would be appreciated. Thanks!

**Comment by asmecher** [comment]
Hi @jimnault -- if you're looking for tech support, I'd suggest posting in the support forum (https://forum.pkp.sfu.ca). If it turns out to be a bug, we can migrate it over here.
