### ISSUE TITLE
Can't activate plugin

### ISSUE THREAD

**Issue by knjigor** [pkp/pdfJsViewer#5]
Hi, I don't know am I missing something but I can't activate plugin. I have followed instructions:

1. copy files to /plugins/generic/pdfJsViewer folder
2. Run the upgrade script
3. Enable plugin trough interface (activate) 

But result is same, on windows machines pdf's are displayed in Adobe reader plugin, and in Kubuntu 14.04 Firefox i get message that browser doesn't have plugin installed. 

We are currently using OJS 2.3.7.0 (with plan to upgrade it to latest version ASAP).

Thanx for help

**Comment by asmecher** [comment]
@knjigor, this plugin is written for OJS 2.4.x and is not compatible with earlier releases. I'd suggest upgrading to OJS 2.4.x.
