### ISSUE TITLE
PDF.js v2.0.943 (build: dc98bf76) Message: Failed to fetch

### ISSUE THREAD

**Issue by ArthurEzenwanne** [pkp/pdfJsViewer#56]
Getting the above message while trying to view an OJS article using the default PDF.js viewer.

![image](https://user-images.githubusercontent.com/8554462/93108673-00b62900-f6ab-11ea-8461-9cc6f7ff4f48.png)

**Comment by asmecher** [comment]
@ArthurEzenwanne, I'd suggest looking at the page source to determine what PDF download URL is being used by pdf.js to try to fetch the PDF file; try opening that directly in the browser and see what the result is.

**Comment by ArthurEzenwanne** [comment]
Thanks @asmecher, I will mark this issue as solved. I uninstalled the PDF.js plugin and installed it again. Everything started working well. Thanks for your support 😊
