### ISSUE TITLE
kemauan dan kemampuan masyarakat

### ISSUE THREAD

**Issue by afriyanto** [pkp/pdfJsViewer#6]
![cover](https://cloud.githubusercontent.com/assets/12844473/8634659/d59bc96c-282b-11e5-8c89-9054e3dfbddd.png)

**Comment by asmecher** [comment]
@afriyanto, you're posting this in the wrong place.

**Comment by afriyanto** [comment]
sorry.. i want to posting pdf but ... i have message ....Something went really wrong, and we can't pro........ and i try posting jpg and i got it.. give me...and please help me.. im newbie...

**Comment by asmecher** [comment]
@afriyanto, what are you trying to do?

**Comment by afriyanto** [comment]
tell me.. how I can upload pdf file in this box..

**Comment by asmecher** [comment]
@afriyanto, are you trying to publish a journal? This is our software code repository, not a place to publish journals. Can you describe more generally what you are trying to do?

**Comment by afriyanto** [comment]
thanks,,
