### ISSUE TITLE
iframe URLs encoding broke with EZProxy

### ISSUE THREAD

**Issue by wangra8** [pkp/pdfJsViewer#60]
Hi Everyone,

This is an old issue that has reappeared, so I'm opening a new issue here and will provide a PR shortly. More discussion can be found here, but I will summarize the issue here as well. https://github.com/pkp/pkp-lib/issues/6246

An Iter journal subscriber reported 2 weeks back that EZProzy suddenly stopped rewriting URLs. For context, here is more information about our EZProxy setup. 

At the end of the Iter Stanza file the following worked fine.

```
Find jps.library.utoronto.ca
Replace ^sjps.library.utoronto.ca^

```

Then in the past few months a different resource that we proxy introduced this line into EZP's config.txt.
This additional line interfered with the JavaScript Find/Replace. 

```
DJ	utoronto.ca
```
After removing DJ utoronto.ca, the Find/Replace worked again. The problem is not specific to OJS. We were able to replicate identical behaviour with other domains that we host. And just in case, we're also currently on EZProxy version 6.5.1 GA. 

The fix required changes to the following lines:

```
<script type="text/javascript">
// Creating iframe's src in JS instead of Smarty so that EZProxy-using sites can find our domain in $pdfUrl and do their rewrites on it.
            $(document).ready(function() {ldelim}
            var urlBase = "{$pluginUrl}/pdf.js/web/viewer.html?file=";
            var pdfUrl = "{$pdfUrl}";
            var encodedPdfUrl = encodeURIComponent(pdfUrl);
            encodedPdfUrl = encodedPdfUrl.replace("https%3A%2F%2F", "https://").replace("http%3A%2F%2F", "http://");
            $("#pdfCanvasContainer > iframe").attr("src", urlBase + encodedPdfUrl);
            {rdelim});
</script>

```

A PR is opened here, please let me know if I can assist with any changes or suggestions.  Thank you! https://github.com/pkp/pdfJsViewer/pull/61/files

Take care and stay safe, 
Rachel

**Comment by asmecher** [comment]
Are you able to shed any light on the reason the additional `DJ` stanza interferes with what is an otherwise-working config? That seems the source of the problem, and I don't have an EZProxy setup here to experiment with. (@jnugent, your feedback on this is welcome too!)

**Comment by wangra8** [comment]
Hi @asmecher 

I will do my best to answer, this is information that has been shared with me:

"We've found that if "DJ utoronto.ca" is contained in one stanza, it may interfere with other stanzas for resources at higher level domains in utoronto, like "library.utoronto.ca. We've identified it was preventing Find/Replace function for jps.library.utoronto.ca and [othersubdomain].library.utoronto.ca. Subscribers tend to update one stanza without reviewing potential conflicts in the entire configuration. So there is a potential that this will happen again. " 

I hope that makes it clearer, let me know, I can ask for more insight. 

Take care,
Rachel

**Comment by jnugent** [comment]
I wish I could offer more insight - my ezProxy experience is about a decade old now, and I also don't have an installation to test with.  @wangra8 the way that you've described it there, that sounds like a bug in ezProxy to me.  While I understand that a less specific stanza can match more specific ones, it'd be nice if ezProxy didn't do that and kept things as specifically matching as possible.

**Comment by wangra8** [comment]
Thank you @jnugent for the reply, I must admit my EZproxy experience is very minimal, I've been poking my awesome colleagues for more insight to get down to the core of the issue. Let me know if there's still gaps in understanding, happy to do more poking haha 😄  Take care all!

**Comment by asmecher** [comment]
Rachel, I'm afraid I have to agree with Jason that this sounds like an EZProxy bug or configuration problem, if that configuration change affected other domains including non-OJS sites. I'll close this issue for now, but if you (or someone else) is able to shed more light on the OJS interaction, please post it here!

**Comment by jnugent** [comment]
I know this is a closed issue, but we just implemented @wangra8's fix to restore access to an institution.  This was for an older 3.1.2 installation so I don't know if the patch is still relevant for newer versions of OJS but it definitely solved the issue for us in this case.

**Comment by asmecher** [comment]
@jnugent, you're talking about [this PR](https://github.com/pkp/pdfJsViewer/pull/61), right? I'm hesitant to merge that because it looks like the string replace on http and https is a work-around for a double-encoding situation. It's possible that EZProxy requires this for some reason but I suspect it's more likely that the URL is being escaped twice or something and the string replace is a work-around to reverse it. If that's right, then I'd rather a solution that doesn't double-escape as other characters are likely to cause problems eventually. In any case, it needs to be reviewed with both a test environment and an eye for where escaping should be applied and where not.
